[package]
name = "climp"
version = "1.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["cargo"] }
crossterm = "0.27.0"
dialoguer = "0.11.0"
id3 = "1.12.0"
ratatui = { version = "0.26.0", features = ["all-widgets", "termion"]}
